### ISSUE TITLE
minimum config

### ISSUE THREAD

**Issue by patagoniahiker** [mirhagk/CloudAtCostAPI#2]
Hey, trying out your lib
1.   What is the bare minimum required in the config to send the request. 
2.   Where are the client key located, is it in the panel under settings, I do not see it.

**Comment by mirhagk** [comment]
You need a credential file with

```
key = exampleKeyHere
login = yourLogin
```

Then you pass this file in by doing `CloudAtCostAPIConsole.exe -cred credentials.txt --list-servers`

Both the key and the login can be found in the panel under settings. You do need to click the generate API key the first time you use it.

You will also need to add your IP to the comma separated list of "API Access IP".

**Comment by patagoniahiker** [comment]
thanks :+1:  the call results in timeout, has the format changed?
